#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "commafeed"
name = "CommaFeed"
description.en = "Personal RSS reader"
description.fr = "Lecteur RSS personnel"

version = "5.3.4~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://www.commafeed.com/"
demo = "https://www.commafeed.com/#/app/category/all"
code = "https://github.com/Athou/commafeed"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "commafeed"
    in_subdir = false
    extract = false
    url = "https://github.com/Athou/commafeed/releases/download/5.3.4/commafeed-5.3.4-h2-linux-x86_64-runner"
    sha256 = "cae7ed82706119e7599e5bb5012a6733a83a25bc5946382d8fd1ac2904500e59"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 8082
